import type { Config, Context } from '@netlify/functions';
import { canResetAdminAccountPassword, changeAdminPassword, clearAdminSessionCookie, requireAuthenticatedAdmin } from './_shared/auth.mts';
import { database } from './_shared/database.mts';
import { enforceSameOrigin, errorResponse, json, readJsonObject, RequestError } from './_shared/http.mts';
import { hashPassword } from './_shared/password.mts';
import { validateAdminPassword } from './_shared/adminPassword.mts';
interface ManagedAccountRow { id:string; created_by_staff_user_id:string|null; }
export default async function handler(request:Request,context:Context):Promise<Response>{if(request.method!=='POST')return json({error:'Method not allowed.'},405);try{enforceSameOrigin(request);const actor=await requireAuthenticatedAdmin(request);const accountId=context.params.id;if(!accountId)throw new RequestError(400,'Admin account ID is required.');const db=database();const targets=(await db.sql`SELECT id,created_by_staff_user_id FROM staff_users WHERE id=${accountId} AND role IN ('admin','super_admin') LIMIT 1`) as ManagedAccountRow[];const target=targets[0];if(!target)throw new RequestError(404,'Admin account not found.');const isSelf=actor.userId===target.id;if(!canResetAdminAccountPassword(actor,target.id,target.created_by_staff_user_id))throw new RequestError(403,'You are not authorized to reset this Admin account password.');const body=await readJsonObject(request);const passwordHash=await hashPassword(validateAdminPassword(body.password));await changeAdminPassword(accountId,passwordHash);if(isSelf)clearAdminSessionCookie(context);return json({changed:true,reauthenticationRequired:isSelf});}catch(error){return errorResponse(error);}}
export const config:Config={path:'/api/admin/accounts/:id/password',method:'POST'};
