import React, { useEffect, useMemo, useState } from 'react';
import { AdminPrincipal, LoyaltyPerk, LoyaltySettings, MenuItem } from '../types';
import { loyaltyConfigService } from '../services/loyaltyConfigService';
import { promoVoucherService, PromoVoucher } from '../services/promoVoucherService';

interface RewardsViewProps { onShowNotification:(msg:string)=>void; menuItems?:MenuItem[]; admin?:AdminPrincipal|null; }

const defaults:LoyaltySettings={welcomeEnabled:false,welcomeStamps:0,welcomePoints:0,stampMinimumPurchase:0,stampsPerQualifyingOrder:1,pointsMinimumPurchase:0,pointsMode:'ratio',fixedPoints:0,pointsPerCurrency:1,currencyUnit:10,stampCycle:10};
const blankPerk=(menuItems:MenuItem[]):LoyaltyPerk=>({id:'',name:'',description:'',rewardSource:'menu',menuItemId:menuItems[0]?.id||'',customItemName:'',redemptionType:'points',redemptionCost:100,active:true});

export const RewardsView:React.FC<RewardsViewProps>=({onShowNotification,menuItems=[],admin})=>{
  const [settings,setSettings]=useState<LoyaltySettings>(defaults); const [perks,setPerks]=useState<LoyaltyPerk[]>([]); const [vouchers,setVouchers]=useState<PromoVoucher[]>([]); const [loading,setLoading]=useState(true); const [form,setForm]=useState<LoyaltyPerk>(blankPerk(menuItems)); const [editing,setEditing]=useState(false); const [saving,setSaving]=useState(false);
  const [voucherForm,setVoucherForm]=useState({code:'',description:'',discountType:'percentage' as 'percentage'|'fixed',discountValue:10,minimumOrderAmount:0,maxUses:0,expiresAt:''});
  const [voucherSaving,setVoucherSaving]=useState(false);
  const load=async()=>{try{const [data,activeVouchers]=await Promise.all([loyaltyConfigService.get(),promoVoucherService.listActive()]);setSettings(data.settings||defaults);setPerks(data.perks||[]);setVouchers(activeVouchers||[]);}catch(e){onShowNotification(e instanceof Error?e.message:'Unable to load loyalty configuration.');}finally{setLoading(false);}};
  useEffect(()=>{load();},[]); useEffect(()=>{if(!form.menuItemId&&menuItems[0])setForm(p=>({...p,menuItemId:menuItems[0].id}));},[menuItems]);
  const menuNames=useMemo(()=>new Map(menuItems.map(i=>[i.id,i.name])),[menuItems]);
  const saveSettings=async()=>{setSaving(true);try{const r=await loyaltyConfigService.saveSettings(settings);setSettings(r.settings);onShowNotification('Rewards & Loyalty settings saved.');}catch(e){onShowNotification(e instanceof Error?e.message:'Unable to save loyalty settings.');}finally{setSaving(false);}};
  const savePerk=async()=>{setSaving(true);try{const r=await loyaltyConfigService.savePerk(form);setPerks(p=>[r.perk,...p.filter(x=>x.id!==r.perk.id)]);setForm(blankPerk(menuItems));setEditing(false);onShowNotification('Reward perk saved.');}catch(e){onShowNotification(e instanceof Error?e.message:'Unable to save reward perk.');}finally{setSaving(false);}};
  const generateVoucher=async()=>{setVoucherSaving(true);try{const voucher=await promoVoucherService.create({...voucherForm,code:voucherForm.code.trim().toUpperCase(),discountValue:Number(voucherForm.discountValue),minimumOrderAmount:Number(voucherForm.minimumOrderAmount),maxUses:Number(voucherForm.maxUses),expiresAt:voucherForm.expiresAt||null});setVouchers(v=>[voucher,...v]);setVoucherForm({code:'',description:'',discountType:'percentage',discountValue:10,minimumOrderAmount:0,maxUses:0,expiresAt:''});onShowNotification(`Promo voucher ${voucher.code} created.`);}catch(e){onShowNotification(e instanceof Error?e.message:'Unable to create promo voucher.');}finally{setVoucherSaving(false);}};
  if(loading)return <div className="pt-20 pb-28 px-4">Loading Rewards & Loyalty…</div>;
  if(admin?.role!=='SUPER_ADMIN')return <div className="pt-20 pb-28 px-4 max-w-5xl mx-auto"><div className="p-6 rounded-2xl bg-[#f9f2f0] border border-[#dec1af]"><h2 className="font-serif text-2xl font-bold text-[#26170c]">Rewards & Loyalty</h2><p className="text-sm text-[#4f453f] mt-2">Only Super Admin can change loyalty rules or perks.</p><div className="mt-4 space-y-2">{perks.filter(p=>p.active).map(p=><div key={p.id} className="p-3 bg-white rounded-xl border"><b>{p.name}</b><div className="text-xs text-[#81756e]">{p.description}</div></div>)}</div></div></div>;
  return <div className="pt-20 pb-28 px-3 sm:px-5 max-w-5xl mx-auto space-y-5">
    <header><h2 className="font-serif text-2xl sm:text-3xl font-bold text-[#26170c]">iLuvKeyks Rewards & Loyalty</h2><p className="text-sm text-[#4f453f]">Super Admin controls how customers earn, what they can redeem, and promotional vouchers.</p></header>
    <section className="bg-[#f9f2f0] border border-[#dec1af] rounded-2xl p-4 sm:p-5 space-y-4"><div><h3 className="font-serif text-lg font-bold">New Customer Welcome Reward</h3><p className="text-xs text-[#81756e]">No welcome reward is granted unless you enable it.</p></div><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={settings.welcomeEnabled} onChange={e=>setSettings({...settings,welcomeEnabled:e.target.checked})}/> Enable welcome reward on registration</label><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><label className="text-xs font-bold">Starting digital stamps<input type="number" min="0" className="w-full mt-1 p-2.5 rounded-xl border" value={settings.welcomeStamps} onChange={e=>setSettings({...settings,welcomeStamps:Math.max(0,Number(e.target.value)||0)})}/></label><label className="text-xs font-bold">Starting reward points<input type="number" min="0" className="w-full mt-1 p-2.5 rounded-xl border" value={settings.welcomePoints} onChange={e=>setSettings({...settings,welcomePoints:Math.max(0,Number(e.target.value)||0)})}/></label></div></section>
    <section className="bg-[#f9f2f0] border border-[#dec1af] rounded-2xl p-4 sm:p-5 space-y-4"><div><h3 className="font-serif text-lg font-bold">Digital Stamp Card — Dine-In / Takeout</h3><p className="text-xs text-[#81756e]">Customers earn stamps only when the eligible purchase reaches your minimum.</p></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><label className="text-xs font-bold">Minimum eligible purchase (₱)<input type="number" min="0" step="0.01" className="w-full mt-1 p-2.5 rounded-xl border" value={settings.stampMinimumPurchase} onChange={e=>setSettings({...settings,stampMinimumPurchase:Math.max(0,Number(e.target.value)||0)})}/></label><label className="text-xs font-bold">Stamps per qualifying order<input type="number" min="1" className="w-full mt-1 p-2.5 rounded-xl border" value={settings.stampsPerQualifyingOrder} onChange={e=>setSettings({...settings,stampsPerQualifyingOrder:Math.max(1,Number(e.target.value)||1)})}/></label><label className="text-xs font-bold">Stamps to complete card<input type="number" min="1" className="w-full mt-1 p-2.5 rounded-xl border" value={settings.stampCycle} onChange={e=>setSettings({...settings,stampCycle:Math.max(1,Number(e.target.value)||1)})}/></label></div></section>
    <section className="bg-[#f9f2f0] border border-[#dec1af] rounded-2xl p-4 sm:p-5 space-y-4"><div><h3 className="font-serif text-lg font-bold">Reward Points — Delivery</h3><p className="text-xs text-[#81756e]">Delivery customers earn points only when the eligible purchase reaches your minimum.</p></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3"><label className="text-xs font-bold">Minimum eligible purchase (₱)<input type="number" min="0" step="0.01" className="w-full mt-1 p-2.5 rounded-xl border" value={settings.pointsMinimumPurchase} onChange={e=>setSettings({...settings,pointsMinimumPurchase:Math.max(0,Number(e.target.value)||0)})}/></label><label className="text-xs font-bold">Earning method<select className="w-full mt-1 p-2.5 rounded-xl border" value={settings.pointsMode} onChange={e=>setSettings({...settings,pointsMode:e.target.value as 'fixed'|'ratio'})}><option value="ratio">Points per ₱ spent</option><option value="fixed">Fixed points per order</option></select></label>{settings.pointsMode==='ratio'?<><label className="text-xs font-bold">Points<input type="number" min="0" step="0.01" className="w-full mt-1 p-2.5 rounded-xl border" value={settings.pointsPerCurrency} onChange={e=>setSettings({...settings,pointsPerCurrency:Math.max(0,Number(e.target.value)||0)})}/></label><label className="text-xs font-bold">Per ₱ amount<input type="number" min="0.01" step="0.01" className="w-full mt-1 p-2.5 rounded-xl border" value={settings.currencyUnit} onChange={e=>setSettings({...settings,currencyUnit:Math.max(.01,Number(e.target.value)||.01)})}/></label></>:<label className="text-xs font-bold">Fixed points<input type="number" min="0" className="w-full mt-1 p-2.5 rounded-xl border" value={settings.fixedPoints} onChange={e=>setSettings({...settings,fixedPoints:Math.max(0,Number(e.target.value)||0)})}/></label>}</div><button disabled={saving} onClick={saveSettings} className="px-4 py-2.5 rounded-xl bg-[#26170c] text-white text-xs font-bold disabled:opacity-50">{saving?'Saving…':'Save Loyalty Settings'}</button></section>
    <section className="bg-[#f9f2f0] border border-[#dec1af] rounded-2xl p-4 sm:p-5 space-y-4"><div className="flex items-center justify-between gap-2"><div><h3 className="font-serif text-lg font-bold">Promo Vouchers</h3><p className="text-xs text-[#81756e]">Generate codes that customers can enter in the Order Bag. Set 0 uses for unlimited redemptions.</p></div></div><div className="bg-white rounded-xl border p-4 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
      <label className="text-xs font-bold">Promo Code<input className="w-full mt-1 p-2.5 rounded-xl border uppercase" placeholder="e.g. SEPTEMBER10" maxLength={32} value={voucherForm.code} onChange={e=>setVoucherForm({...voucherForm,code:e.target.value.toUpperCase()})}/></label>
      <label className="text-xs font-bold">Description<input className="w-full mt-1 p-2.5 rounded-xl border" placeholder="e.g. September customer promo" value={voucherForm.description} onChange={e=>setVoucherForm({...voucherForm,description:e.target.value})}/></label>
      <label className="text-xs font-bold">Discount Type<select className="w-full mt-1 p-2.5 rounded-xl border" value={voucherForm.discountType} onChange={e=>setVoucherForm({...voucherForm,discountType:e.target.value as 'percentage'|'fixed'})}><option value="percentage">Percentage Discount</option><option value="fixed">Fixed ₱ Discount</option></select></label>
      <label className="text-xs font-bold">Discount Value {voucherForm.discountType==='percentage'?'(%)':'(₱)'}<input type="number" min="0.01" step="0.01" className="w-full mt-1 p-2.5 rounded-xl border" placeholder={voucherForm.discountType==='percentage'?'e.g. 10':'e.g. 50'} value={voucherForm.discountValue} onChange={e=>setVoucherForm({...voucherForm,discountValue:Number(e.target.value)})}/></label>
      <label className="text-xs font-bold">Minimum Order Amount (₱)<input type="number" min="0" step="0.01" className="w-full mt-1 p-2.5 rounded-xl border" placeholder="0 = no minimum" value={voucherForm.minimumOrderAmount} onChange={e=>setVoucherForm({...voucherForm,minimumOrderAmount:Number(e.target.value)})}/></label>
      <label className="text-xs font-bold">Maximum Uses<input type="number" min="0" className="w-full mt-1 p-2.5 rounded-xl border" placeholder="0 = unlimited" value={voucherForm.maxUses} onChange={e=>setVoucherForm({...voucherForm,maxUses:Number(e.target.value)})}/></label>
      <label className="text-xs font-bold">Expiry Date & Time<input type="datetime-local" className="w-full mt-1 p-2.5 rounded-xl border" value={voucherForm.expiresAt} onChange={e=>setVoucherForm({...voucherForm,expiresAt:e.target.value})}/></label>
      <div className="flex items-end"><button disabled={voucherSaving} onClick={generateVoucher} className="w-full px-4 py-2.5 rounded-xl bg-[#26170c] text-white text-xs font-bold disabled:opacity-50">{voucherSaving?'Generating…':'Generate Promo Code'}</button></div>
    </div><div className="space-y-2">{vouchers.map(v=><div key={v.id} className="bg-white border rounded-xl p-3 flex flex-col sm:flex-row justify-between gap-3"><div><div className="font-bold text-sm tracking-wide">{v.code}</div><div className="text-xs text-[#81756e]">{v.description||'Promo voucher'} • {v.discountType==='percentage'?`${v.discountValue}% off`:`₱${v.discountValue.toFixed(2)} off`} • Min ₱{v.minimumOrderAmount.toFixed(2)} • {v.maxUses===0?'Unlimited':`${v.usedCount}/${v.maxUses} uses`}{v.expiresAt?` • Expires ${new Date(v.expiresAt).toLocaleString()}`:''}</div></div><div className="flex gap-2 items-start"><button onClick={async()=>{const updated=await promoVoucherService.toggle(v.id);setVouchers(prev=>prev.filter(x=>x.id!==v.id));onShowNotification(`${updated.code} ${updated.active?'activated':'deactivated'}.`);}} className="px-3 py-1.5 rounded-full bg-[#e1e1c9] text-[11px] font-bold">Deactivate</button><button onClick={async()=>{await promoVoucherService.remove(v.id);setVouchers(prev=>prev.filter(x=>x.id!==v.id));onShowNotification('Promo voucher deleted.');}} className="px-3 py-1.5 rounded-full bg-[#ffdad6] text-[11px] font-bold">Delete</button></div></div>)}</div></section>
    <section className="bg-[#f9f2f0] border border-[#dec1af] rounded-2xl p-4 sm:p-5 space-y-4"><div className="flex items-center justify-between gap-2"><div><h3 className="font-serif text-lg font-bold">Redeemable Perks</h3><p className="text-xs text-[#81756e]">Choose a menu product or any custom item such as a cap or mug.</p></div><button onClick={()=>{setForm(blankPerk(menuItems));setEditing(true);}} className="px-3 py-2 rounded-xl bg-[#26170c] text-white text-xs font-bold">+ Add Perk</button></div>{editing&&<div className="bg-white rounded-xl border p-4 grid grid-cols-1 sm:grid-cols-2 gap-3"><input className="p-2.5 rounded-xl border" placeholder="Reward name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><select className="p-2.5 rounded-xl border" value={form.rewardSource} onChange={e=>setForm({...form,rewardSource:e.target.value as 'menu'|'custom'})}><option value="menu">Existing Menu Product</option><option value="custom">Custom Item</option></select>{form.rewardSource==='menu'?<select className="p-2.5 rounded-xl border" value={form.menuItemId||''} onChange={e=>setForm({...form,menuItemId:e.target.value})}>{menuItems.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>:<input className="p-2.5 rounded-xl border" placeholder="Custom item e.g. iLuvKeyks Mug" value={form.customItemName||''} onChange={e=>setForm({...form,customItemName:e.target.value})}/>}<input className="p-2.5 rounded-xl border" placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><select className="p-2.5 rounded-xl border" value={form.redemptionType} onChange={e=>setForm({...form,redemptionType:e.target.value as 'stamps'|'points'})}><option value="points">Reward Points</option><option value="stamps">Digital Stamps</option></select><input type="number" min="1" className="p-2.5 rounded-xl border" placeholder="Required points / stamps" value={form.redemptionCost} onChange={e=>setForm({...form,redemptionCost:Math.max(1,Number(e.target.value)||1)})}/><div className="sm:col-span-2 flex gap-2"><button disabled={saving} onClick={savePerk} className="px-4 py-2 rounded-xl bg-[#5e604d] text-white text-xs font-bold">Save Perk</button><button onClick={()=>setEditing(false)} className="px-4 py-2 rounded-xl bg-[#eee6e2] text-xs font-bold">Cancel</button></div></div>}
      <div className="space-y-2">{perks.map(p=><div key={p.id} className="bg-white border rounded-xl p-3 flex flex-col sm:flex-row justify-between gap-3"><div><div className="font-bold text-sm">{p.name}</div><div className="text-xs text-[#81756e]">{p.description}</div><div className="text-[11px] font-semibold mt-1">{p.rewardSource==='menu'?`Menu: ${menuNames.get(p.menuItemId||'')||'Product removed'}`:`Custom: ${p.customItemName}`} • {p.redemptionCost} {p.redemptionType}</div></div><div className="flex gap-2 items-start"><button onClick={()=>{setForm(p);setEditing(true);}} className="px-3 py-1.5 rounded-full bg-[#f3ecea] text-[11px] font-bold">Edit</button><button onClick={async()=>{await loyaltyConfigService.togglePerk(p.id);await load();}} className="px-3 py-1.5 rounded-full bg-[#e1e1c9] text-[11px] font-bold">{p.active?'Active':'Inactive'}</button><button onClick={async()=>{await loyaltyConfigService.deletePerk(p.id);await load();}} className="px-3 py-1.5 rounded-full bg-[#ffdad6] text-[11px] font-bold">Delete</button></div></div>)}</div>
    </section>
  </div>;
};
